### ISSUE TITLE
Create Users

### ISSUE THREAD

**Issue by Ryaguy15** [mtuopensource/TechChat#16]
### Explain the Task
When at the login activity, the user can click the sign up button and move to a new activity to create their account

**Comment by ajwgeek** [comment]
To register a new user, send a POST to /api/users/ with the fields email and password. If the user was successfully created, the status code will be 201 CREATED. 

If not enough information was provided, the status code will be 400 BAD REQUEST.

**Comment by Ryaguy15** [comment]
One quick question. If I get that 201 code, will i get the user info from the server?
@ajwgeek

**Comment by ajwgeek** [comment]
Yep! You should get a JSON object with user info.
