### ISSUE TITLE
Alias Generator

### ISSUE THREAD

**Issue by I-Smith** [mtuopensource/TechChat#19]
## Task

We would like each user to be assigned a random alias for each thread in which they participate. In order to do this we need a generator program (alias.py).

The program:
  * Has large list of adjectives in an array
  * Has a large list of famous Scientists/Engineers/Innovators from the past
  * When called, randomly produce an alias of the form [Adjective] [Famous person] [Random number].

The base file has been made.
If anyone has any ideas for adjectives or people feel free to add them as you think of them.

---
## Other Ideas

Later in time we may want to separate the adjectives and names into dedicated text files, just something to think about.

**Comment by Javen-W** [comment]
Should be include a random number 1-10 at the end as well?

**Comment by I-Smith** [comment]
That could be a nice addition, but shouldn't take long to implement. If it's something you'd like to add then go ahead and we can discuss it later.

**Comment by Javen-W** [comment]
If you can create the program, I can help contribute to the content.
