### ISSUE TITLE
Bug In DB

### ISSUE THREAD

**Issue by Ryaguy15** [mtuopensource/TechChat#28]
# Bug
Issue with Backend Database
### Expected Behavior

- Get a normal JSON response 
---

### Actual Behavoir
- Error

http://ci.mtuopensource.club:8000/api/users/login/
1.11.10
OperationalError
no such table: django_session
/var/lib/jenkins/.local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py in execute, line 328
/usr/bin/python3
3.5.2
['/var/lib/jenkins/workspace/TechChat Backend/backend',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/var/lib/jenkins/.local/lib/python3.5/site-packages',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages']
Fri, 23 Feb 2018 15:50:23 +0000

----

### Steps to Reproduce Error
- Make a Post Request to /api/users/login
---

@ajwgeek

**Comment by ajwgeek** [comment]
I've modified the Jenkins build script, so it should run the migrations automatically now.

## Build
```
killall -q python3 || true
cd "$WORKSPACE/backend"
pip3 install -r requirements.txt
python3 manage.py migrate
python3 manage.py test
```

## Post Build
```
cd "$WORKSPACE/backend"
pip3 install -r requirements.txt
python3 manage.py migrate
python3 manage.py runserver 0.0.0.0:8000 > /dev/null 2>&1 &
```
