### ISSUE TITLE
Create a cookie parser class

### ISSUE THREAD

**Issue by Ryaguy15** [mtuopensource/TechChat#52]
# Task
### Explain the Task
  There are places in the code base, where the response header needs to be scanned for cookie data. This code has been repeated a few times throughout the code base, and a class that can handle this would be nice.

**Comment by dominiksitar** [comment]
Hi, can I work on this?

**Comment by Ryaguy15** [comment]
I would say no because we are changing from a cookie based authentication to a token based one, and your work would be irrelevant. I would recommend that you work on #59. There's a lot of creativity you can leverage
