### ISSUE TITLE
Web - email/password filler text persists

### ISSUE THREAD

**Issue by I-Smith** [mtuopensource/TechChat#56]
# Bug
The images below show the initial screen, then the behavior when typing into the text fields:
![image](https://user-images.githubusercontent.com/23102836/45700293-133c0d00-bb3a-11e8-9e9a-79a953585dff.png)

![image](https://user-images.githubusercontent.com/23102836/45700205-eb4ca980-bb39-11e8-86de-f04c7f0cadff.png)

### Steps to Reproduce Error
Follow the link to the hosted version of TechChat and start filling in email/password fields

---

# Task
### Explain the Task
Need to fix the page so that when text is entered, the filler disappears. Should just be a few basic lines of code, easily done by new members.

**Comment by jgolatkar** [comment]
@I-Smith has the issue been fixed? When I try to reproduce the error on hosted version, there's no such behavior.
![capture1](https://user-images.githubusercontent.com/14250174/46216503-beed1600-c30d-11e8-8b39-da692e9b404e.PNG)
![capture2](https://user-images.githubusercontent.com/14250174/46216519-c4e2f700-c30d-11e8-8797-f42cb78d1573.PNG)

**Comment by I-Smith** [comment]
It appears to be fixed.
@ajwgeek is that a result of the code rework you were working on?

**Comment by Ryaguy15** [comment]
This is also an issue with the thread creation form as well
