### ISSUE TITLE
Add "make migration" to the proc file

### ISSUE THREAD

**Issue by Ryaguy15** [mtuopensource/TechChat#60]
# Task
### Explain the Task
When new models get added, django requires make migrations to get the new models into the db
Add this to the proc file so the server will run this command

**Comment by casscauley** [comment]
Normally you would run `makemigrations` locally and commit them to the repository. I noticed your migrations file is empty. Is there a reason you're running this on deploy and not during development?

**Comment by Ryaguy15** [comment]
We have been changing the database structure quite often while we're working towards a solution we like, and having the migrations commits repo seemed to be unnecessary. We could have migrations in the repo itself soon when we have a finalized roadmap. This was mainly meant for a double checking on the production server due to some testing on other branches
